// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDySWjJc4PkR45v0_Q6CnPy6yHSHv7FMp4',
    appId: '1:192805778631:web:295f527a1d27f6f8523ae2',
    messagingSenderId: '192805778631',
    projectId: 'agrishop-6c644',
    authDomain: 'agrishop-6c644.firebaseapp.com',
    storageBucket: 'agrishop-6c644.appspot.com',
    measurementId: 'G-82T0VG4G6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDks5VGcIlSXbavm3S61TPcxV-L1vT1HGg',
    appId: '1:192805778631:android:9fe423e03e13938f523ae2',
    messagingSenderId: '192805778631',
    projectId: 'agrishop-6c644',
    storageBucket: 'agrishop-6c644.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAgKbroNrh4lj-dnSqaN6gGmsVagXKOJI',
    appId: '1:192805778631:ios:0f3f852848e22300523ae2',
    messagingSenderId: '192805778631',
    projectId: 'agrishop-6c644',
    storageBucket: 'agrishop-6c644.appspot.com',
    iosBundleId: 'com.example.agriShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAgKbroNrh4lj-dnSqaN6gGmsVagXKOJI',
    appId: '1:192805778631:ios:cc2dc42c4933806a523ae2',
    messagingSenderId: '192805778631',
    projectId: 'agrishop-6c644',
    storageBucket: 'agrishop-6c644.appspot.com',
    iosBundleId: 'com.example.agriShop.RunnerTests',
  );
}
